In [8]:
import pandas as pd
import matplotlib.pyplot as plt
birds = pd.read_csv('birds.csv')
birds.head()

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,Black-bellied whistling-duck,Dendrocygna autumnalis,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,47.0,56.0,652.0,1020.0,76.0,94.0
1,Fulvous whistling-duck,Dendrocygna bicolor,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,45.0,53.0,712.0,1050.0,85.0,93.0
2,Snow goose,Anser caerulescens,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,79.0,2050.0,4050.0,135.0,165.0
3,Ross's goose,Anser rossii,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,57.3,64.0,1066.0,1567.0,113.0,116.0
4,Greater white-fronted goose,Anser albifrons,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,81.0,1930.0,3310.0,130.0,165.0

In [9]:
birds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 443 entries, 0 to 442
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                443 non-null    object
 1   ScientificName      443 non-null    object
 2   Category            443 non-null    object
 3   Order               443 non-null    object
 4   Family              443 non-null    object
 5   Genus               443 non-null    object
 6   ConservationStatus  443 non-null    object
 7   MinLength           443 non-null    float64
 8   MaxLength           443 non-null    float64
 9   MinBodyMass         443 non-null    float64
 10  MaxBodyMass         443 non-null    float64
 11  MinWingspan         443 non-null    float64
 12  MaxWingspan         443 non-null    float64
dtypes: float64(6), object(7)
memory usage: 45.1+ KB

In [10]:
birds.tail()

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
438,Blue grosbeak,Passerina caerulea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,14.0,19.0,26.0,31.5,26.0,29.0
439,Lazuli bunting,Passerina amoena,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,13.0,15.0,13.0,18.0,22.0,22.0
440,Indigo bunting,Passerina cyanea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,11.5,15.0,11.2,21.4,18.0,23.0
441,Painted bunting,Passerina ciris,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,12.0,14.0,13.0,19.0,21.0,23.0
442,Dickcissel,Spiza americana,Cardinals/Allies,Passeriformes,Cardinalidae,Spiza,LC,14.0,16.0,25.6,38.4,24.8,26.0

In [11]:
birds.isnull()

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,False,False,False,False,False,False,False,False,False,False,False,False,False
439,False,False,False,False,False,False,False,False,False,False,False,False,False
440,False,False,False,False,False,False,False,False,False,False,False,False,False
441,False,False,False,False,False,False,False,False,False,False,False,False,False
442,False,False,False,False,False,False,False,False,False,False,False,False,False

In [12]:
example1 = birds.dropna()
example1

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,Black-bellied whistling-duck,Dendrocygna autumnalis,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,47.0,56.0,652.0,1020.0,76.0,94.0
1,Fulvous whistling-duck,Dendrocygna bicolor,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,45.0,53.0,712.0,1050.0,85.0,93.0
2,Snow goose,Anser caerulescens,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,79.0,2050.0,4050.0,135.0,165.0
3,Ross's goose,Anser rossii,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,57.3,64.0,1066.0,1567.0,113.0,116.0
4,Greater white-fronted goose,Anser albifrons,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,81.0,1930.0,3310.0,130.0,165.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,Blue grosbeak,Passerina caerulea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,14.0,19.0,26.0,31.5,26.0,29.0
439,Lazuli bunting,Passerina amoena,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,13.0,15.0,13.0,18.0,22.0,22.0
440,Indigo bunting,Passerina cyanea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,11.5,15.0,11.2,21.4,18.0,23.0
441,Painted bunting,Passerina ciris,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,12.0,14.0,13.0,19.0,21.0,23.0
442,Dickcissel,Spiza americana,Cardinals/Allies,Passeriformes,Cardinalidae,Spiza,LC,14.0,16.0,25.6,38.4,24.8,26.0

In [13]:
birds.dropna(axis='columns')

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,Black-bellied whistling-duck,Dendrocygna autumnalis,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,47.0,56.0,652.0,1020.0,76.0,94.0
1,Fulvous whistling-duck,Dendrocygna bicolor,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,45.0,53.0,712.0,1050.0,85.0,93.0
2,Snow goose,Anser caerulescens,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,79.0,2050.0,4050.0,135.0,165.0
3,Ross's goose,Anser rossii,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,57.3,64.0,1066.0,1567.0,113.0,116.0
4,Greater white-fronted goose,Anser albifrons,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,81.0,1930.0,3310.0,130.0,165.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,Blue grosbeak,Passerina caerulea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,14.0,19.0,26.0,31.5,26.0,29.0
439,Lazuli bunting,Passerina amoena,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,13.0,15.0,13.0,18.0,22.0,22.0
440,Indigo bunting,Passerina cyanea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,11.5,15.0,11.2,21.4,18.0,23.0
441,Painted bunting,Passerina ciris,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,12.0,14.0,13.0,19.0,21.0,23.0
442,Dickcissel,Spiza americana,Cardinals/Allies,Passeriformes,Cardinalidae,Spiza,LC,14.0,16.0,25.6,38.4,24.8,26.0

In [14]:
birds.dropna(axis='rows', thresh=3)

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,Black-bellied whistling-duck,Dendrocygna autumnalis,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,47.0,56.0,652.0,1020.0,76.0,94.0
1,Fulvous whistling-duck,Dendrocygna bicolor,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,45.0,53.0,712.0,1050.0,85.0,93.0
2,Snow goose,Anser caerulescens,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,79.0,2050.0,4050.0,135.0,165.0
3,Ross's goose,Anser rossii,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,57.3,64.0,1066.0,1567.0,113.0,116.0
4,Greater white-fronted goose,Anser albifrons,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,81.0,1930.0,3310.0,130.0,165.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,Blue grosbeak,Passerina caerulea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,14.0,19.0,26.0,31.5,26.0,29.0
439,Lazuli bunting,Passerina amoena,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,13.0,15.0,13.0,18.0,22.0,22.0
440,Indigo bunting,Passerina cyanea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,11.5,15.0,11.2,21.4,18.0,23.0
441,Painted bunting,Passerina ciris,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,12.0,14.0,13.0,19.0,21.0,23.0
442,Dickcissel,Spiza americana,Cardinals/Allies,Passeriformes,Cardinalidae,Spiza,LC,14.0,16.0,25.6,38.4,24.8,26.0

In [15]:
birds.fillna(0)

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,Black-bellied whistling-duck,Dendrocygna autumnalis,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,47.0,56.0,652.0,1020.0,76.0,94.0
1,Fulvous whistling-duck,Dendrocygna bicolor,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,45.0,53.0,712.0,1050.0,85.0,93.0
2,Snow goose,Anser caerulescens,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,79.0,2050.0,4050.0,135.0,165.0
3,Ross's goose,Anser rossii,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,57.3,64.0,1066.0,1567.0,113.0,116.0
4,Greater white-fronted goose,Anser albifrons,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,81.0,1930.0,3310.0,130.0,165.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,Blue grosbeak,Passerina caerulea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,14.0,19.0,26.0,31.5,26.0,29.0
439,Lazuli bunting,Passerina amoena,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,13.0,15.0,13.0,18.0,22.0,22.0
440,Indigo bunting,Passerina cyanea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,11.5,15.0,11.2,21.4,18.0,23.0
441,Painted bunting,Passerina ciris,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,12.0,14.0,13.0,19.0,21.0,23.0
442,Dickcissel,Spiza americana,Cardinals/Allies,Passeriformes,Cardinalidae,Spiza,LC,14.0,16.0,25.6,38.4,24.8,26.0

In [16]:
birds.fillna(method='ffill')

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,Black-bellied whistling-duck,Dendrocygna autumnalis,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,47.0,56.0,652.0,1020.0,76.0,94.0
1,Fulvous whistling-duck,Dendrocygna bicolor,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,45.0,53.0,712.0,1050.0,85.0,93.0
2,Snow goose,Anser caerulescens,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,79.0,2050.0,4050.0,135.0,165.0
3,Ross's goose,Anser rossii,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,57.3,64.0,1066.0,1567.0,113.0,116.0
4,Greater white-fronted goose,Anser albifrons,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,81.0,1930.0,3310.0,130.0,165.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,Blue grosbeak,Passerina caerulea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,14.0,19.0,26.0,31.5,26.0,29.0
439,Lazuli bunting,Passerina amoena,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,13.0,15.0,13.0,18.0,22.0,22.0
440,Indigo bunting,Passerina cyanea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,11.5,15.0,11.2,21.4,18.0,23.0
441,Painted bunting,Passerina ciris,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,12.0,14.0,13.0,19.0,21.0,23.0
442,Dickcissel,Spiza americana,Cardinals/Allies,Passeriformes,Cardinalidae,Spiza,LC,14.0,16.0,25.6,38.4,24.8,26.0

In [18]:
birds.fillna(method='ffill', axis=1)

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,Black-bellied whistling-duck,Dendrocygna autumnalis,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,47.0,56.0,652.0,1020.0,76.0,94.0
1,Fulvous whistling-duck,Dendrocygna bicolor,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,45.0,53.0,712.0,1050.0,85.0,93.0
2,Snow goose,Anser caerulescens,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,79.0,2050.0,4050.0,135.0,165.0
3,Ross's goose,Anser rossii,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,57.3,64.0,1066.0,1567.0,113.0,116.0
4,Greater white-fronted goose,Anser albifrons,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,81.0,1930.0,3310.0,130.0,165.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,Blue grosbeak,Passerina caerulea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,14.0,19.0,26.0,31.5,26.0,29.0
439,Lazuli bunting,Passerina amoena,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,13.0,15.0,13.0,18.0,22.0,22.0
440,Indigo bunting,Passerina cyanea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,11.5,15.0,11.2,21.4,18.0,23.0
441,Painted bunting,Passerina ciris,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,12.0,14.0,13.0,19.0,21.0,23.0
442,Dickcissel,Spiza americana,Cardinals/Allies,Passeriformes,Cardinalidae,Spiza,LC,14.0,16.0,25.6,38.4,24.8,26.0

Removing duplicate data

In [19]:
birds.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
438    False
439    False
440    False
441    False
442    False
Length: 443, dtype: bool

In [20]:
birds.drop_duplicates()

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,Black-bellied whistling-duck,Dendrocygna autumnalis,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,47.0,56.0,652.0,1020.0,76.0,94.0
1,Fulvous whistling-duck,Dendrocygna bicolor,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,45.0,53.0,712.0,1050.0,85.0,93.0
2,Snow goose,Anser caerulescens,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,79.0,2050.0,4050.0,135.0,165.0
3,Ross's goose,Anser rossii,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,57.3,64.0,1066.0,1567.0,113.0,116.0
4,Greater white-fronted goose,Anser albifrons,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,81.0,1930.0,3310.0,130.0,165.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,Blue grosbeak,Passerina caerulea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,14.0,19.0,26.0,31.5,26.0,29.0
439,Lazuli bunting,Passerina amoena,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,13.0,15.0,13.0,18.0,22.0,22.0
440,Indigo bunting,Passerina cyanea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,11.5,15.0,11.2,21.4,18.0,23.0
441,Painted bunting,Passerina ciris,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,12.0,14.0,13.0,19.0,21.0,23.0
442,Dickcissel,Spiza americana,Cardinals/Allies,Passeriformes,Cardinalidae,Spiza,LC,14.0,16.0,25.6,38.4,24.8,26.0

In [21]:
birds.drop_duplicates(['Family'])

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,Black-bellied whistling-duck,Dendrocygna autumnalis,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,47.0,56.0,652.0,1020.0,76.0,94.0
45,Northern bobwhite,Colinus virginianus,New World quail,Galliformes,Odontophoridae,Colinus,NT,24.0,28.0,129.0,173.0,33.0,38.0
46,Wild turkey,Meleagris gallopavo,Pheasants/Grouse/Allies,Galliformes,Phasianidae,Meleagris,LC,110.0,115.0,2500.0,10800.0,125.0,144.0
55,Pied-billed grebe,Podilymbus podiceps,Grebes,Podicipediformes,Podicipedidae,Podilymbus,LC,31.0,38.0,253.0,568.0,45.0,62.0
61,Rock pigeon,Columba livia,Pigeons/Doves,Columbiformes,Columbidae,Columba,LC,29.0,37.0,238.0,380.0,62.0,72.0
69,Groove-billed ani,Crotophaga sulcirostris,Cuckoos,Cuculiformes,Cuculidae,Crotophaga,LC,34.0,34.0,70.0,90.0,41.0,46.0
72,Common nighthawk,Chordeiles minor,Nightjars/Allies,Caprimulgiformes,Caprimulgidae,Chordeiles,LC,22.0,25.0,55.0,98.0,51.0,61.0
76,Chimney swift,Chaetura pelagica,Swifts,Apodiformes,Apodidae,Chaetura,VU,12.0,15.0,17.0,30.0,27.0,30.0
78,Mexican violetear,Colibri thalassinus,Hummingbirds,Apodiformes,Trochilidae,Colibri,LC,9.7,12.0,4.8,5.6,12.0,12.0
85,King rail,Rallus elegans,Rails/Gallinules/Coots,Gruiformes,Rallidae,Rallus,NT,15.5,19.0,290.0,290.0,48.0,48.0
93,Sandhill crane,Antigone canadensis,Cranes,Gruiformes,Gruidae,Antigone,LC,80.0,136.0,4020.0,4570.0,200.0,200.0
95,Black-necked stilt,Himantopus mexicanus,Stilts and avocets,Charadriiformes,Recurvirostridae,Himantopus,LC,35.0,39.0,150.0,176.0,71.5,75.5
97,Black-bellied plover,Pluvialis squatarola,Plovers/Lapwings,Charadriiformes,Charadriidae,Pluvialis,LC,27.0,30.0,190.0,280.0,71.0,83.0
104,Upland sandpiper,Bartramia longicauda,Sandpipers/Allies,Charadriiformes,Scolopacidae,Bartramia,LC,30.0,30.0,170.0,170.0,66.0,66.0
138,Pomarine jaeger,Stercorarius pomarinus,Skuas and jaegers,Charadriiformes,Stercorariidae,Stercorarius,LC,46.0,67.0,540.0,920.0,110.0,138.0
141,Dovekie,Alle alle,Auks/Murres/Puffins,Charadriiformes,Alcidae,Alle,LC,19.0,21.0,134.0,204.0,34.0,38.0
145,Black-legged kittiwake,Rissa tridactyla,Gulls/Terns/Skimmers,Charadriiformes,Laridae,Rissa,VU,37.0,41.0,305.0,525.0,91.0,105.0
173,Red-throated loon,Gavia stellata,Loons,Gaviiformes,Gaviidae,Gavia,LC,53.0,69.0,1000.0,2700.0,91.0,120.0
177,Northern fulmar,Fulmarus glacialis,Shearwaters and petrels,Procellariiformes,Procellariidae,Fulmarus,LC,46.0,46.0,450.0,1000.0,102.0,112.0
178,Wood stork,Mycteria americana,Storks,Ciconiiformes,Ciconiidae,Mycteria,LC,83.0,115.0,2000.0,3300.0,140.0,180.0
179,Magnificent frigatebird,Fregata magnificens,Frigatebirds,Suliformes,Fregatidae,Fregata,LC,89.0,114.0,1100.0,1590.0,217.0,244.0
180,Double-crested cormorant,Phalacrocorax auritus,Cormorants/Shags,Suliformes,Phalacrocoracidae,Phalacrocorax,LC,70.0,90.0,1200.0,2500.0,114.0,123.0
182,American white pelican,Pelecanus erythrorhynchos,Pelicans,Pelecaniformes,Pelecanidae,Pelecanus,LC,130.0,180.0,3500.0,13600.0,240.0,300.0
184,American bittern,Botaurus lentiginosus,Herons/Egrets/Bitterns,Pelecaniformes,Ardeidae,Botarus,LC,58.0,85.0,370.0,1072.0,92.0,115.0
195,White ibis,Eudocimus albus,Ibises/Spoonbills,Pelecaniformes,Threskiornithidae,Eudocimus,LC,53.0,70.0,592.7,1261.0,90.0,105.0
199,Black vulture,Coragyps atratus,New World vultures,Cathartiformes,Cathartidae,Coragyps,LC,56.0,74.0,1600.0,3000.0,133.0,167.0
201,Osprey,Pandion haliaetus,Osprey,Accipitriformes,Pandionidae,Pandion,LC,50.0,66.0,900.0,2100.0,127.0,180.0
202,White-tailed kite,Elanus leucurus,Hawks/Eagles,Accipitriformes,Accipitridae,Elanus,LC,35.0,43.0,250.0,380.0,88.0,102.0
217,Barn owl,Tyto alba,Barn-owls,Strigiformes,Tytonidae,Tyto,LC,33.0,39.0,224.0,710.0,80.0,95.0
218,Eastern screech-owl,Megascops asio,Owls,Strigiformes,Strigidae,Megascops,LC,16.0,25.0,121.0,244.0,46.0,61.0
229,Belted kingfisher,Megaeryle alcyon,Kingfishers,Coraciiformes,Alcedinidae,Megaceryle,LC,28.0,35.0,113.0,178.0,48.0,58.0
230,Lewis's woodpecker,Melanerpes lewis,Woodpeckers,Piciformes,Picidae,Melanerpes,LC,26.0,28.0,88.0,138.0,49.0,52.0
242,Crested caracara,Caracara cheriway,Falcons /Caracaras,Falconformes,Falconidae,Caracara,LC,49.0,63.0,701.0,1387.0,118.0,132.0
248,Ash-throated flycatcher,Myiarchus cinerascens,Tyrant flycatchers,Passeriformes,Tyrannidae,Myiarchus,LC,19.0,22.0,20.0,37.0,30.0,32.0
267,Loggerhead shrike,Lanius ludovicianus,Shrikes,Passeriformes,Laniidae,Lanius,NT,20.0,23.0,35.0,50.0,28.0,32.0
269,White-eyed vireo,Vireo griseus,Vireos/Shrike-babblers/Erpornis,Passeriformes,Vireonidae,Vireo,LC,11.0,13.0,10.0,14.0,17.0,17.0
276,Canada jay,Perisoreus canadensis,Crows/Jays/Magpies,Passeriformes,Corvidae,Perisoreus,LC,25.0,33.0,65.0,70.0,45.0,45.0
282,Horned lark,Eremophila alpestris,Larks,Passeriformes,Alaudidae,Eremophila,LC,16.0,20.0,28.0,48.0,30.0,34.0
283,Bank swallow,Riparia riparia,Swallows,Passeriformes,Hirundinidae,Riparia,LC,12.0,14.0,10.2,18.8,25.0,33.0
290,Black-capped chickadee,Poecile atricapilla,Tits/Chickadees/Titmice,Passeriformes,Paridae,Poecile,LC,12.0,15.0,9.0,14.0,16.0,21.0
293,Red-breasted nuthatch,Sitta canadensis,Nuthatches,Passeriformes,Sittidae,Sitta,LC,11.0,11.0,9.9,9.9,22.0,22.0
296,Brown creeper,Certhia americana,Treecreepers,Passeriformes,Certhiidae,Certhia,LC,12.0,14.0,5.0,10.0,17.0,20.0
297,Rock wren,Salpinctes obsoletus,Wrens,Passeriformes,Troglodytidae,Salpinctes,LC,12.5,15.0,15.0,18.0,22.0,24.0
304,Blue-gray gnatcatcher,Polioptila caerulea,Gnatcatchers,Passeriformes,Polioptilidae,Polioptila,LC,10.0,13.0,5.0,7.0,16.0,16.0
305,American dipper,Cinclus mexicanus,Dippers,Passeriformes,Cinclidae,Cinclus,LC,16.5,16.5,46.0,46.0,23.0,23.0
306,Golden-crowned kinglet,Regulus satrapa,Kinglets,Passeriformes,Regulidae,Regulus,LC,8.0,11.0,4.0,7.8,14.0,18.0
308,Northern wheatear,Oenanthe oenanthe,Old World flycatchers,Passeriformes,Muscicapidae,Oenanthe,LC,14.5,16.0,17.0,30.0,26.0,32.0
309,Eastern bluebird,Sialia sialis,Thrushes/Allies,Passeriformes,Turdidae,Sialia,LC,16.0,21.0,27.0,34.0,25.0,32.0
320,Gray catbird,Dumetella carolinensis,Mockingbirds/Thrashers,Passeriformes,Mimidae,Dumetella,LC,20.5,24.0,23.2,56.5,22.0,30.0
325,European starling,Sturnus vulgaris,Starlings,Passeriformes,Sturnidae,Sturnus,LC,19.0,23.0,58.0,101.0,31.0,44.0
326,Bohemian waxwing,Bombycilla garrulus,Waxwings,Passeriformes,Bombycillidae,Bombycilla,LC,19.0,23.0,55.0,55.0,32.0,35.5
328,House sparrow,Passer domesticus,Old World sparrows,Passeriformes,Passeridae,Passer,LC,14.0,18.0,24.0,29.5,19.0,25.0
330,American pipit,Anthus rubescens,Wagtails/Pitpits,Passeriformes,Motacillidae,Anthus,LC,16.0,16.0,22.0,22.0,24.0,24.0
332,Brambling,Fringilla montifringilla,Finches/Euphonias/Allies,Passeriformes,Fringillidae,Fringilla,LC,16.0,16.0,23.0,29.0,25.0,26.0
345,Lapland longspur,Calcarius lapponicus,Longspurs/Snow buntings,Passeriformes,Calcariidae,Calcarius,LC,15.0,16.0,22.3,33.1,22.0,29.0
350,Grasshopper sparrow,Ammodramus savannarum,New World sparrows,Passeriformes,Passerellidae,Ammodramus,LC,10.0,14.0,13.8,28.4,17.5,17.5
376,Yellow-breasted chat,Icteria virens,Yellow-breasted chat,Passeriformes,Icteridae,Icteria,LC,17.0,19.1,20.2,33.8,23.0,27.0
391,Ovenbird,Seiurus aurocapilla,New World warblers,Passeriformes,Parulidae,Seiurus,LC,11.0,16.0,14.0,28.8,19.0,26.0
432,Summer tanager,Piranga rubra,Cardinals/Allies,Passeriformes,Cardinalidae,Piranga,LC,17.0,17.0,29.0,29.0,28.0,30.0

In [22]:
birds.shape

(443, 13)

In [23]:
birds.columns

Index(['Name', 'ScientificName', 'Category', 'Order', 'Family', 'Genus',
       'ConservationStatus', 'MinLength', 'MaxLength', 'MinBodyMass',
       'MaxBodyMass', 'MinWingspan', 'MaxWingspan'],
      dtype='object')

In [24]:
birds.info

<bound method DataFrame.info of                              Name          ScientificName  \
0    Black-bellied whistling-duck  Dendrocygna autumnalis
1          Fulvous whistling-duck     Dendrocygna bicolor
2                      Snow goose      Anser caerulescens
3                    Ross's goose            Anser rossii
4     Greater white-fronted goose         Anser albifrons
..                            ...                     ...
438                 Blue grosbeak      Passerina caerulea
439                Lazuli bunting        Passerina amoena
440                Indigo bunting        Passerina cyanea
441               Painted bunting         Passerina ciris
442                    Dickcissel         Spiza americana

                  Category          Order        Family        Genus  \
0    Ducks/Geese/Waterfowl   Anseriformes      Anatidae  Dendrocygna
1    Ducks/Geese/Waterfowl   Anseriformes      Anatidae  Dendrocygna
2    Ducks/Geese/Waterfowl   Anseriformes      Anatidae        Anser
3    Ducks/Geese/Waterfowl   Anseriformes      Anatidae        Anser
4    Ducks/Geese/Waterfowl   Anseriformes      Anatidae        Anser
..                     ...            ...           ...          ...
438       Cardinals/Allies  Passeriformes  Cardinalidae    Passerina
439       Cardinals/Allies  Passeriformes  Cardinalidae    Passerina
440       Cardinals/Allies  Passeriformes  Cardinalidae    Passerina
441       Cardinals/Allies  Passeriformes  Cardinalidae    Passerina
442       Cardinals/Allies  Passeriformes  Cardinalidae        Spiza

    ConservationStatus  MinLength  MaxLength  MinBodyMass  MaxBodyMass  \
0                   LC       47.0       56.0        652.0       1020.0
1                   LC       45.0       53.0        712.0       1050.0
2                   LC       64.0       79.0       2050.0       4050.0
3                   LC       57.3       64.0       1066.0       1567.0
4                   LC       64.0       81.0       1930.0       3310.0
..                 ...        ...        ...          ...          ...
438                 LC       14.0       19.0         26.0         31.5
439                 LC       13.0       15.0         13.0         18.0
440                 LC       11.5       15.0         11.2         21.4
441                 LC       12.0       14.0         13.0         19.0
442                 LC       14.0       16.0         25.6         38.4

     MinWingspan  MaxWingspan
0           76.0         94.0
1           85.0         93.0
2          135.0        165.0
3          113.0        116.0
4          130.0        165.0
..           ...          ...
438         26.0         29.0
439         22.0         22.0
440         18.0         23.0
441         21.0         23.0
442         24.8         26.0

[443 rows x 13 columns]>

In [25]:
birds.describe

<bound method NDFrame.describe of                              Name          ScientificName  \
0    Black-bellied whistling-duck  Dendrocygna autumnalis
1          Fulvous whistling-duck     Dendrocygna bicolor
2                      Snow goose      Anser caerulescens
3                    Ross's goose            Anser rossii
4     Greater white-fronted goose         Anser albifrons
..                            ...                     ...
438                 Blue grosbeak      Passerina caerulea
439                Lazuli bunting        Passerina amoena
440                Indigo bunting        Passerina cyanea
441               Painted bunting         Passerina ciris
442                    Dickcissel         Spiza americana

                  Category          Order        Family        Genus  \
0    Ducks/Geese/Waterfowl   Anseriformes      Anatidae  Dendrocygna
1    Ducks/Geese/Waterfowl   Anseriformes      Anatidae  Dendrocygna
2    Ducks/Geese/Waterfowl   Anseriformes      Anatidae        Anser
3    Ducks/Geese/Waterfowl   Anseriformes      Anatidae        Anser
4    Ducks/Geese/Waterfowl   Anseriformes      Anatidae        Anser
..                     ...            ...           ...          ...
438       Cardinals/Allies  Passeriformes  Cardinalidae    Passerina
439       Cardinals/Allies  Passeriformes  Cardinalidae    Passerina
440       Cardinals/Allies  Passeriformes  Cardinalidae    Passerina
441       Cardinals/Allies  Passeriformes  Cardinalidae    Passerina
442       Cardinals/Allies  Passeriformes  Cardinalidae        Spiza

    ConservationStatus  MinLength  MaxLength  MinBodyMass  MaxBodyMass  \
0                   LC       47.0       56.0        652.0       1020.0
1                   LC       45.0       53.0        712.0       1050.0
2                   LC       64.0       79.0       2050.0       4050.0
3                   LC       57.3       64.0       1066.0       1567.0
4                   LC       64.0       81.0       1930.0       3310.0
..                 ...        ...        ...          ...          ...
438                 LC       14.0       19.0         26.0         31.5
439                 LC       13.0       15.0         13.0         18.0
440                 LC       11.5       15.0         11.2         21.4
441                 LC       12.0       14.0         13.0         19.0
442                 LC       14.0       16.0         25.6         38.4

     MinWingspan  MaxWingspan
0           76.0         94.0
1           85.0         93.0
2          135.0        165.0
3          113.0        116.0
4          130.0        165.0
..           ...          ...
438         26.0         29.0
439         22.0         22.0
440         18.0         23.0
441         21.0         23.0
442         24.8         26.0

[443 rows x 13 columns]>

In [26]:
birds.head()

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,Black-bellied whistling-duck,Dendrocygna autumnalis,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,47.0,56.0,652.0,1020.0,76.0,94.0
1,Fulvous whistling-duck,Dendrocygna bicolor,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,45.0,53.0,712.0,1050.0,85.0,93.0
2,Snow goose,Anser caerulescens,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,79.0,2050.0,4050.0,135.0,165.0
3,Ross's goose,Anser rossii,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,57.3,64.0,1066.0,1567.0,113.0,116.0
4,Greater white-fronted goose,Anser albifrons,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,81.0,1930.0,3310.0,130.0,165.0

In [27]:
birds.head(10)

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,Black-bellied whistling-duck,Dendrocygna autumnalis,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,47.0,56.0,652.0,1020.0,76.0,94.0
1,Fulvous whistling-duck,Dendrocygna bicolor,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,45.0,53.0,712.0,1050.0,85.0,93.0
2,Snow goose,Anser caerulescens,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,79.0,2050.0,4050.0,135.0,165.0
3,Ross's goose,Anser rossii,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,57.3,64.0,1066.0,1567.0,113.0,116.0
4,Greater white-fronted goose,Anser albifrons,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,81.0,1930.0,3310.0,130.0,165.0
5,Brant,Branta bernicla,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Branta,LC,55.0,66.0,880.0,2200.0,206.0,121.0
6,Cackling goose,Branta hutchinsii,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Branta,LC,63.0,65.0,1398.0,2380.0,108.0,111.0
7,Canada goose,Branta canadensis,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Branta,LC,75.0,110.0,2600.0,6500.0,127.0,185.0
8,Mute swan,Cygnus olor,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Cygnus,LC,125.0,170.0,9200.0,14300.0,200.0,240.0
9,Trumpeter swan,Cygnus buccinator,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Cygnus,LC,138.0,180.0,7000.0,13600.0,185.0,250.0

In [28]:
birds.tail()

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
438,Blue grosbeak,Passerina caerulea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,14.0,19.0,26.0,31.5,26.0,29.0
439,Lazuli bunting,Passerina amoena,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,13.0,15.0,13.0,18.0,22.0,22.0
440,Indigo bunting,Passerina cyanea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,11.5,15.0,11.2,21.4,18.0,23.0
441,Painted bunting,Passerina ciris,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,12.0,14.0,13.0,19.0,21.0,23.0
442,Dickcissel,Spiza americana,Cardinals/Allies,Passeriformes,Cardinalidae,Spiza,LC,14.0,16.0,25.6,38.4,24.8,26.0

In [29]:
birds.tail(10)

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
433,Scarlet tanager,Piranga olivacea,Cardinals/Allies,Passeriformes,Cardinalidae,Piranga,LC,16.0,19.0,23.5,38.0,25.0,30.0
434,Western tanager,Piranga ludoviciana,Cardinals/Allies,Passeriformes,Cardinalidae,Piranga,LC,16.0,19.0,24.0,36.0,29.0,29.0
435,Northern cardinal,Cardinalis cardinalis,Cardinals/Allies,Passeriformes,Cardinalidae,Cardinalis,LC,21.0,23.5,33.6,65.0,25.0,31.0
436,Rose-breasted grosbeak,Pheucticus ludovicianus,Cardinals/Allies,Passeriformes,Cardinalidae,Pheucticus,LC,18.0,22.0,35.0,65.0,29.0,33.0
437,Black-headed grosbeak,Pheucticus melanocephalus,Cardinals/Allies,Passeriformes,Cardinalidae,Pheucticus,LC,18.0,19.0,34.0,49.0,32.0,32.0
438,Blue grosbeak,Passerina caerulea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,14.0,19.0,26.0,31.5,26.0,29.0
439,Lazuli bunting,Passerina amoena,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,13.0,15.0,13.0,18.0,22.0,22.0
440,Indigo bunting,Passerina cyanea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,11.5,15.0,11.2,21.4,18.0,23.0
441,Painted bunting,Passerina ciris,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,12.0,14.0,13.0,19.0,21.0,23.0
442,Dickcissel,Spiza americana,Cardinals/Allies,Passeriformes,Cardinalidae,Spiza,LC,14.0,16.0,25.6,38.4,24.8,26.0

Missing Data

In [30]:
birds.isnull()

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,False,False,False,False,False,False,False,False,False,False,False,False,False
439,False,False,False,False,False,False,False,False,False,False,False,False,False
440,False,False,False,False,False,False,False,False,False,False,False,False,False
441,False,False,False,False,False,False,False,False,False,False,False,False,False
442,False,False,False,False,False,False,False,False,False,False,False,False,False

In [31]:
birds.notnull()

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,True,True,True,True,True,True,True,True,True,True,True,True,True
439,True,True,True,True,True,True,True,True,True,True,True,True,True
440,True,True,True,True,True,True,True,True,True,True,True,True,True
441,True,True,True,True,True,True,True,True,True,True,True,True,True
442,True,True,True,True,True,True,True,True,True,True,True,True,True

In [32]:
birds.dropna()

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,Black-bellied whistling-duck,Dendrocygna autumnalis,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,47.0,56.0,652.0,1020.0,76.0,94.0
1,Fulvous whistling-duck,Dendrocygna bicolor,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,45.0,53.0,712.0,1050.0,85.0,93.0
2,Snow goose,Anser caerulescens,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,79.0,2050.0,4050.0,135.0,165.0
3,Ross's goose,Anser rossii,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,57.3,64.0,1066.0,1567.0,113.0,116.0
4,Greater white-fronted goose,Anser albifrons,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,81.0,1930.0,3310.0,130.0,165.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,Blue grosbeak,Passerina caerulea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,14.0,19.0,26.0,31.5,26.0,29.0
439,Lazuli bunting,Passerina amoena,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,13.0,15.0,13.0,18.0,22.0,22.0
440,Indigo bunting,Passerina cyanea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,11.5,15.0,11.2,21.4,18.0,23.0
441,Painted bunting,Passerina ciris,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,12.0,14.0,13.0,19.0,21.0,23.0
442,Dickcissel,Spiza americana,Cardinals/Allies,Passeriformes,Cardinalidae,Spiza,LC,14.0,16.0,25.6,38.4,24.8,26.0

In [33]:
birds.fillna(2)

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,Black-bellied whistling-duck,Dendrocygna autumnalis,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,47.0,56.0,652.0,1020.0,76.0,94.0
1,Fulvous whistling-duck,Dendrocygna bicolor,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,45.0,53.0,712.0,1050.0,85.0,93.0
2,Snow goose,Anser caerulescens,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,79.0,2050.0,4050.0,135.0,165.0
3,Ross's goose,Anser rossii,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,57.3,64.0,1066.0,1567.0,113.0,116.0
4,Greater white-fronted goose,Anser albifrons,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,81.0,1930.0,3310.0,130.0,165.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,Blue grosbeak,Passerina caerulea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,14.0,19.0,26.0,31.5,26.0,29.0
439,Lazuli bunting,Passerina amoena,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,13.0,15.0,13.0,18.0,22.0,22.0
440,Indigo bunting,Passerina cyanea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,11.5,15.0,11.2,21.4,18.0,23.0
441,Painted bunting,Passerina ciris,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,12.0,14.0,13.0,19.0,21.0,23.0
442,Dickcissel,Spiza americana,Cardinals/Allies,Passeriformes,Cardinalidae,Spiza,LC,14.0,16.0,25.6,38.4,24.8,26.0

In [34]:
birds.isnull().sum()

Name                  0
ScientificName        0
Category              0
Order                 0
Family                0
Genus                 0
ConservationStatus    0
MinLength             0
MaxLength             0
MinBodyMass           0
MaxBodyMass           0
MinWingspan           0
MaxWingspan           0
dtype: int64

In [35]:
birds.notnull().sum()

Name                  443
ScientificName        443
Category              443
Order                 443
Family                443
Genus                 443
ConservationStatus    443
MinLength             443
MaxLength             443
MinBodyMass           443
MaxBodyMass           443
MinWingspan           443
MaxWingspan           443
dtype: int64

Dealing with missing data

In [37]:
# Dropping null values
example3 = birds.dropna()
example3

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,Black-bellied whistling-duck,Dendrocygna autumnalis,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,47.0,56.0,652.0,1020.0,76.0,94.0
1,Fulvous whistling-duck,Dendrocygna bicolor,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,45.0,53.0,712.0,1050.0,85.0,93.0
2,Snow goose,Anser caerulescens,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,79.0,2050.0,4050.0,135.0,165.0
3,Ross's goose,Anser rossii,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,57.3,64.0,1066.0,1567.0,113.0,116.0
4,Greater white-fronted goose,Anser albifrons,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,81.0,1930.0,3310.0,130.0,165.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,Blue grosbeak,Passerina caerulea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,14.0,19.0,26.0,31.5,26.0,29.0
439,Lazuli bunting,Passerina amoena,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,13.0,15.0,13.0,18.0,22.0,22.0
440,Indigo bunting,Passerina cyanea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,11.5,15.0,11.2,21.4,18.0,23.0
441,Painted bunting,Passerina ciris,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,12.0,14.0,13.0,19.0,21.0,23.0
442,Dickcissel,Spiza americana,Cardinals/Allies,Passeriformes,Cardinalidae,Spiza,LC,14.0,16.0,25.6,38.4,24.8,26.0

In [38]:
birds.dropna(axis='columns')

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,Black-bellied whistling-duck,Dendrocygna autumnalis,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,47.0,56.0,652.0,1020.0,76.0,94.0
1,Fulvous whistling-duck,Dendrocygna bicolor,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,45.0,53.0,712.0,1050.0,85.0,93.0
2,Snow goose,Anser caerulescens,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,79.0,2050.0,4050.0,135.0,165.0
3,Ross's goose,Anser rossii,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,57.3,64.0,1066.0,1567.0,113.0,116.0
4,Greater white-fronted goose,Anser albifrons,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,81.0,1930.0,3310.0,130.0,165.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,Blue grosbeak,Passerina caerulea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,14.0,19.0,26.0,31.5,26.0,29.0
439,Lazuli bunting,Passerina amoena,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,13.0,15.0,13.0,18.0,22.0,22.0
440,Indigo bunting,Passerina cyanea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,11.5,15.0,11.2,21.4,18.0,23.0
441,Painted bunting,Passerina ciris,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,12.0,14.0,13.0,19.0,21.0,23.0
442,Dickcissel,Spiza americana,Cardinals/Allies,Passeriformes,Cardinalidae,Spiza,LC,14.0,16.0,25.6,38.4,24.8,26.0

In [39]:
birds.dropna(axis='rows', thresh=3)

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,Black-bellied whistling-duck,Dendrocygna autumnalis,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,47.0,56.0,652.0,1020.0,76.0,94.0
1,Fulvous whistling-duck,Dendrocygna bicolor,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,45.0,53.0,712.0,1050.0,85.0,93.0
2,Snow goose,Anser caerulescens,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,79.0,2050.0,4050.0,135.0,165.0
3,Ross's goose,Anser rossii,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,57.3,64.0,1066.0,1567.0,113.0,116.0
4,Greater white-fronted goose,Anser albifrons,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,81.0,1930.0,3310.0,130.0,165.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,Blue grosbeak,Passerina caerulea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,14.0,19.0,26.0,31.5,26.0,29.0
439,Lazuli bunting,Passerina amoena,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,13.0,15.0,13.0,18.0,22.0,22.0
440,Indigo bunting,Passerina cyanea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,11.5,15.0,11.2,21.4,18.0,23.0
441,Painted bunting,Passerina ciris,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,12.0,14.0,13.0,19.0,21.0,23.0
442,Dickcissel,Spiza americana,Cardinals/Allies,Passeriformes,Cardinalidae,Spiza,LC,14.0,16.0,25.6,38.4,24.8,26.0

Filling null values

In [40]:
birds_data_values = birds.iloc[:, 7:14]

In [41]:
birds_data_values

     MinLength  MaxLength  MinBodyMass  MaxBodyMass  MinWingspan  MaxWingspan
0         47.0       56.0        652.0       1020.0         76.0         94.0
1         45.0       53.0        712.0       1050.0         85.0         93.0
2         64.0       79.0       2050.0       4050.0        135.0        165.0
3         57.3       64.0       1066.0       1567.0        113.0        116.0
4         64.0       81.0       1930.0       3310.0        130.0        165.0
..         ...        ...          ...          ...          ...          ...
438       14.0       19.0         26.0         31.5         26.0         29.0
439       13.0       15.0         13.0         18.0         22.0         22.0
440       11.5       15.0         11.2         21.4         18.0         23.0
441       12.0       14.0         13.0         19.0         21.0         23.0
442       14.0       16.0         25.6         38.4         24.8         26.0

[443 rows x 6 columns]

In [42]:
birds_data_values.median()

MinLength      20.5
MaxLength      25.0
MinBodyMass    55.0
MaxBodyMass    89.0
MinWingspan    38.0
MaxWingspan    42.0
dtype: float64

In [43]:
# The median of the first column is
birds_data_values.fillna(birds_data_values["MinLength"].median(),inplace=True)

In [44]:
birds_data_values.fillna(0)

     MinLength  MaxLength  MinBodyMass  MaxBodyMass  MinWingspan  MaxWingspan
0         47.0       56.0        652.0       1020.0         76.0         94.0
1         45.0       53.0        712.0       1050.0         85.0         93.0
2         64.0       79.0       2050.0       4050.0        135.0        165.0
3         57.3       64.0       1066.0       1567.0        113.0        116.0
4         64.0       81.0       1930.0       3310.0        130.0        165.0
..         ...        ...          ...          ...          ...          ...
438       14.0       19.0         26.0         31.5         26.0         29.0
439       13.0       15.0         13.0         18.0         22.0         22.0
440       11.5       15.0         11.2         21.4         18.0         23.0
441       12.0       14.0         13.0         19.0         21.0         23.0
442       14.0       16.0         25.6         38.4         24.8         26.0

[443 rows x 6 columns]

In [45]:
# What happens if you try to fill null values with a string, like ''?
birds_data_values_filled = birds_data_values.fillna('')
birds_data_values_filled

     MinLength  MaxLength  MinBodyMass  MaxBodyMass  MinWingspan  MaxWingspan
0         47.0       56.0        652.0       1020.0         76.0         94.0
1         45.0       53.0        712.0       1050.0         85.0         93.0
2         64.0       79.0       2050.0       4050.0        135.0        165.0
3         57.3       64.0       1066.0       1567.0        113.0        116.0
4         64.0       81.0       1930.0       3310.0        130.0        165.0
..         ...        ...          ...          ...          ...          ...
438       14.0       19.0         26.0         31.5         26.0         29.0
439       13.0       15.0         13.0         18.0         22.0         22.0
440       11.5       15.0         11.2         21.4         18.0         23.0
441       12.0       14.0         13.0         19.0         21.0         23.0
442       14.0       16.0         25.6         38.4         24.8         26.0

[443 rows x 6 columns]

In [46]:
birds_data_values_fill = birds_data_values.fillna(method='ffill')

In [47]:
birds_data_values.fillna(method='ffill', axis=1)

     MinLength  MaxLength  MinBodyMass  MaxBodyMass  MinWingspan  MaxWingspan
0         47.0       56.0        652.0       1020.0         76.0         94.0
1         45.0       53.0        712.0       1050.0         85.0         93.0
2         64.0       79.0       2050.0       4050.0        135.0        165.0
3         57.3       64.0       1066.0       1567.0        113.0        116.0
4         64.0       81.0       1930.0       3310.0        130.0        165.0
..         ...        ...          ...          ...          ...          ...
438       14.0       19.0         26.0         31.5         26.0         29.0
439       13.0       15.0         13.0         18.0         22.0         22.0
440       11.5       15.0         11.2         21.4         18.0         23.0
441       12.0       14.0         13.0         19.0         21.0         23.0
442       14.0       16.0         25.6         38.4         24.8         26.0

[443 rows x 6 columns]

What output does example4.fillna(method='bfill', axis=1) produce?

When you apply the fillna() method to a DataFrame with the method='bfill' parameter and axis=1, it fills the missing values using backward fill along the columns. This means that each missing value is replaced with the next non-null value in the same column, moving from top to bottom.

What about example4.fillna(method='ffill') or example4.fillna(method='bfill')?

When you apply the fillna() method to a DataFrame with the method='ffill' parameter, it fills the missing values using forward fill. This means that each missing value is replaced with the last non-null value in the same column, moving from top to bottom.

Similarly, when you apply the fillna() method with the method='bfill' parameter, it fills the missing values using backward fill. This means that each missing value is replaced with the next non-null value in the same column, moving from top to bottom.

Can you think of a longer code snippet to write that can fill all of the null values in example4?

""" for column in df.columns: df[column] = df[column].fillna(0)

"""

Encoding Categorical Data

In [48]:
# LABEL ENCODING
label = pd.DataFrame([
                      [10,'business class'],
                      [20,'first class'],
                      [30, 'economy class'],
                      [40, 'economy class'],
                      [50, 'economy class'],
                      [60, 'business class']
],columns=['ID','class'])
label

   ID           class
0  10  business class
1  20     first class
2  30   economy class
3  40   economy class
4  50   economy class
5  60  business class

In [49]:
class_labels = {'business class':0,'economy class':1,'first class':2}
label['class'] = label['class'].replace(class_labels)
label

   ID  class
0  10      0
1  20      2
2  30      1
3  40      1
4  50      1
5  60      0

In [50]:
# ONE HOT ENCODING
one_hot = pd.DataFrame([
                      [10,'business class'],
                      [20,'first class'],
                      [30, 'economy class'],
                      [40, 'economy class'],
                      [50, 'economy class'],
                      [60, 'business class']
],columns=['ID','class'])

In [51]:
one_hot_data = pd.get_dummies(one_hot,columns=['class'])

In [52]:
one_hot_data

   ID  class_business class  class_economy class  class_first class
0  10                     1                    0                  0
1  20                     0                    0                  1
2  30                     0                    1                  0
3  40                     0                    1                  0
4  50                     0                    1                  0
5  60                     1                    0                  0

In [53]:
# Removing duplicate data
example6 = pd.DataFrame({'letters': ['A','B'] * 2 + ['B'],
                         'numbers': [1, 2, 1, 3, 3]})
example6

  letters  numbers
0       A        1
1       B        2
2       A        1
3       B        3
4       B        3

In [54]:
example6.duplicated()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [55]:
# Dropping duplicates: drop_duplicates
example6.drop_duplicates()

  letters  numbers
0       A        1
1       B        2
3       B        3

In [56]:
example6.drop_duplicates(['letters'])

  letters  numbers
0       A        1
1       B        2